# An Introduction to Programming for scientists

This is software called Jupyter Notebook (or jupyter lab). It lets us combine, text, graphics, stuff from the web, code and the results from the code all into one document. It is a really powerful tool if you need to combine all these things. Plus it works like a graphing calculator too! Can you say math homework? When we run code in jupyter, we use a programming language called "Python". Python is used all over the place, infact it is the primary language behind most of Google's applications on the internet. You can even run your notebooks as a slide show like power point.

### Running it on your computer
If you installed anaconda python on your computer you can start it by searching you computer for **"jupyter"** and then clicking on the icon. A browser window will pop-up which lets you browse the files on your computer. At that point you can open a notebook file (".ipynb") or creat a new one. 

Another option on Windows is to search **"cmd"** to open a command window and type **"jupyter notebook"** without the quotes.

On a Mac you can search **"terminal"** and type **"jupyter notebook"** without the quotes. If that doesn't work search or browse your Applications for **"Anaconda Navigator"** and then click **"Run"** under **"jupyter notebook"**.

There is also a version called **"jupyter lab"**. It works much the same as jupyter notebook, but allows for tabbed windows and a persistant file browswer. To run jupyter lab, just replace **"notebook"** with **"lab"** in all the diretions above.

It doesn't matter if you use **"jupyter notebook"** or **"jupyter lab"**, they both save files as ".ipynb" that will work in both programs. Which one you use is largely personal preference.

### Running it on the internet
There are a few tools online that let you run jupyter notebooks directly in a browswer on a remote server, so you don't need python installed locally. One of those is "Google Colaboratory" https://colab.research.google.com/notebooks/intro.ipynb

### Printing and sharing
You can send folks the jupyter notebook file and all of your outputs will be saved in it! However, if you don't need the person to be able to run your code (aka if you are turning in an assignment) the best way to share you work is to save it as a PDF. Iin "jupyter notebook" You can go up to "File"-->"Print Preview" and then "Print to PDF". In "jupyter lab" go to "File"-->"Export Notebook as"-->"Export as HTML". A new browser tab will open, in print that tab via "Print to PDF".

-----

## Jupyter Notebook Basics

Jupyter Notebook has two main types of "cells". You change a cells type by using the drop down menu in the tool bar which either says "Markdown" or "code". The first type of cell is a "Markdown" cell that is used for typing text. This is a markdown cell. It basically works exactly like a wiki-page. The other type of cell is a "code"

#This is a code cell, I know it is a code cell because of the "In [ ]" to the left. Once a code cell is run a number will appear in it.
#The number is the order in which the cells where run, not necessarily the order on the page. Typically a code cell contains
#code the will run, aka. that will do something. You can however add text that won't run by putting "#" in front of any line
#you don't want to run. This makes it a comment.

While not true in this notebook, I recommend the code cell below always be your first code cell as it load important tools you might need. What is this cell doing?   

    %matplotlib inline                #This tells Jupyter to embed and plots you make in your notebook
    import numpy as np                #This loads the tool called Numpy, that lets you do things with numbers and arrays of numbers
    import scipy as sp                #This loads Scipy that include powerful scientific tools like the ability 
                                      #to fit functions and perform statistics
    import matplotlib.pyplot as plt   #This loads tools to let you make graphs
    from astropy.io import ascii      #This loads tools to let you import CSV files that you create in Exel
    plt.style.use('default')          #This loads the default plotting style
   
For additional references and many examples see these websites:

1. Python [Tutorial](https://docs.python.org/3/tutorial/ )
2. Numpy [Getting Started](https://docs.scipy.org/doc/numpy/user/index.html)
3. Scipy [Reference & Tutorials](https://docs.scipy.org/doc/scipy/reference/)
4. matplotlib [Tutorials](https://matplotlib.org/tutorials/index.html) and [Examples](https://matplotlib.org/gallery/index.html)

In [181]:
%matplotlib notebook
import numpy as np 
import scipy as sp
import matplotlib.pyplot as plt
from astropy.io import ascii
plt.style.use('default')

## Creating and Editing Markdown Cells

To creat a text cell like this one, hight-light an exsisting cell by click to the left of the cell(or pressing esc). This will turn the highlight box "blue". Then selecting "Markdown" from the dropdown box above. Or press "m"

to add a new cell press the "+" icon at top or press esc and the "b" to add a cell below or "a" to add a cell above. By default, new cells are "code" We till talk more about that in a second.

**To edit a cell**, click in the cell, or press "enter" if the cell is highlighted "blue". This will change it to "green" In a text Cell you can do lots of different things like make headers

**To run or render a cell** press "shift+enter" to render the text in a markdown cell or run a code cell. Pressing just "enter" will always add a new line in the current cell.

## Ha I made this

Markdown Examples

# Backround Section

testets etst est test

## Subsection

### sub sub section

###### this is basically just bold
see

*this is how you do italics*
_underline?_
**bold**
***bold and italic***

## Lists
- Item
- Item
 - Nested item
 - nested item
- not nested item
- item
 -    nested item
  - double nested item
- item
  - double nested item

You can even make pretty equations by typing a '\$' then putting in your equation followed by another '\$', for example:


Equations in markdown cell use the LaTex format. For [references](https://en.wikibooks.org/wiki/LaTeX/Mathematics) to other math character

examples
 $F=ma$
 $V=\frac{4}{3} \pi r^3$
 or
 $V=\frac43 \pi r^3$
 but
 $V=\frac423 \pi r^31*213$
 instead
 $V=\frac{42}{3} r^{3121}*3$

Image examples

In [182]:
#You can even embed video with 
from IPython.display import IFrame
#copy and past the "embed" code from a google video between quotes '<iframe goes here>'
IFrame(src="https://www.youtube.com/embed/cbP2N1BQdYc", width="560", height="315")
#now we tell jupyter to treat the iframe like HTML

-----
## What can you do in a code cell?

First a code cell will always have a "In [x]:" to the right of it, where, "x" will either be:
- a number if the cell has been execute, 
- blank if it hasn't executed or, a 
- "$*$" if it is in the process of being executed

Let do some code now. Actually, the video thing and your "first cell" up above are already code!

In [218]:
print("Hello World")

Hello World


When you run cells that are code, jupyter evaluates the code in the cell and ignores the comments. In the cell above, the code is "print("Hello World")" which just prints the text "Hellow World". The output from the excuted cell always shows up below the cell. Lets do some other things

----
## Simple math?

In [219]:
#we can add
3+9

12

In [220]:
#multiply
3*9

27

In [225]:
#powers, you use two astriks **
8**2

64

In [226]:
#all together
((2+2)*2)**2

64

In [228]:
# how about algebra
position = 7 #m
time = 3 #s
position * time

21

In [236]:
#trig functions. Sine 'np.sin()', cosine 'np.cos()', tangent 'np.tan()' and inverse functions 'np.arcsin()', 'np.arccos()', 
np.sin(np.pi / 4)

0.7071067811865475

In [237]:
#be careful though, python assumes your angles are in radians, to get something degrees you have to multiply by 180.0/np.pi
np.sin(45 * (180 / np.pi))

0.8060754911159176

In [191]:
#A couple of points, there are different types of data in python


# anything with a decimal point in it is a "float" and this is what you want to use for 
#"real" data or if you want to calcuate something.

In [192]:
#any number that DOES NOT have a decimal number, is an intiger. Use this for counting

In [193]:
'things between quotes are called strings' #this is for anything that is text like

'things between quotes are called strings'

In [194]:
# We can also assign any type of data to variables and do math on them, even strings! 
# We use the = to define a variable. for instance



In [245]:
#last likely we can make lists of things using brackets and set them to a variable

period1 = 3
period2 = 4
period3 = 5

Avg_Period = (3 + 4 +5)/3
print(Avg_Period)

periods = (3, 4, 5)

avg_period = np.mean(periods)
print(avg_period)

std_period = np.std(periods)
print(std_period)
stds = (1, 1, 2,)
stds_avg = np.mean(stds)
print(stds_avg)

4.0
4.0
0.816496580927726
0.75


In [196]:
# can we take an average?

In [197]:
# what is the standard deviation?

## Plotting

So you have those to list of numbers, what if those were measurements? And you want to make a plot

In [247]:
#Now lets plot this list
x = (0, 1, 2, 3)
y = (1, 3, 4, 5)

plt.plot(x, y)

In [252]:
#What if want to plot dots, in magenta, label the axis and title, and gridlines
plt.figure #creates a new plot
plt.plot(x, y, color='magenta', marker='o', linestyle='none')
plt.xlabel('x')
plt.ylabel('y')
plt.title('y vs x')
plt.grid()

### To save you figure. Right click on the image and select "save image as . . ."
or you can use the plt.savefig() function that will save the file in the folder you are working in for example.

In [200]:
#What if want to plot dots, in magenta, label the axis and title, and gridlines



In [201]:
#You Try it. Make you own list of x values and y values. then copy the code from the cell above



## What if you have two sets of data?

Then just make two sets of variables and use plt.plot() twice!

In [202]:
#first set of data


#second set of data

#First data to plot. We added label for for a legend too!


#First data to plot. We added label for for a legend too!


Lets look at some examples from the matplotlib [Examples](https://matplotlib.org/gallery/index.html) Gallery

This method we are using to plot here works, but if you may notice most examples are a little different. The method used in the examples is the prefered method lets give it shot

In [203]:
#first set of data
x1 = np.array([0.0,1.0,2.0,3.0])
y1 = np.array([1.0,3.0,4.0,5.0])

#second set of data
x2 = np.array([1.0,3.0,5.0,7.0])
y2 = np.array([5.0,6.0,4.0,7.0])

#this new line explicity creates your figure canvas and the "subplot" that gets plotted on it.
#this method allows you to easily create multiple plots on the same canvas & when use the plot()
#function you explicitly tell it where to go
fig,ax = plt.subplots(dpi=200) 

#First data to plot. We added label for for a legend too!
#here instead of "plt.plot()" we now use "ax.plot()" this tells python we want it on the 
#sub plot ax, not some other random plot somewhere in our notebook
ax.plot(x1,y1,label='green',color='green',marker='o',linestyle='None')

#First data to plot. We added label for for a legend too!
ax.plot(x2,y2,label='orange',color='orange',marker='o',linestyle='None')
#The only other difference is now instead of "plt.xlabel" etc., we have to use "ax.set_xlabel"
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_title('y verus x')
ax.legend()
ax.grid()

<IPython.core.display.Javascript object>

------
### Now lets try it with real data!

Go to our spreadsheet of height, show and wingspan data. Select ~10 people over a range of heights (It is sorted by height). and type in the heights for x and their shoe size for y

In [204]:
#You can read in data that you entered in a spread sheet. The simplest way is to save that spreadsheet as a comma
#seperated value table into the SAME folder you have save your jupyter notebook.

#download the "example_data.csv" file from D2L and save it to the SAME folder that you have saved this notebook

# Column Number    Name
# 0                Timestamp
# 1                Name
# 2                starID
# 3                Diameter (squares)
# 4                Area (squares)
 
data=ascii.read("example_data.csv") 
x_real =data.columns[0] #what column has your data you want on the x-axis? The 1st column is column "0"
y_real =data.columns[1] #what column has your data you want on the y-axis? The 1st column is column "0"

In [205]:
#plot the data we imported
plt.plot(x_real,y_real,'o')
plt.xlabel('x')
plt.ylabel('y')
plt.title('y verus x')
plt.legend()
plt.grid()

Now lets collect data in class and see if we can import it and make a graph!
1. Go to https://forms.gle/aWvkNYG6v9iAaGas8 and enter your height, wingspan, birth month & EUR shoesize. 
2. Once all of the class has entered their data. Go here https://docs.google.com/spreadsheets/d/1FF1SBjWv4730_BDoIfXHy4KZASAM_0HsnvyhJ0bzbFo/edit?usp=sharing and download as a CSV file: "File --> Download as --> comma seperated file, current sheet (CSV).
3. Insert two new code cells below and copy the cells above that we used to import and plot the data. Make the edits so you can plot this new data, specifically plot height versus wingspan
  - remember to change the file name to the new file name
  - remember to change the column numbers to the actual column numbers in the new file
  - remember to change the variable names to something new so you don't overwrite the example data we already imported

------

## Lets fit some data (aka add trend lines)

First lets make some fake data that we can then fit. You don't really need to know what is going on here. This data will be like what you would get for a spring oscillating up and down.

In [206]:
# Generate data points with noise
#the number of points to create
num_points = 150  

#create the x data points
#linspace create an array with the length of num_points with values between 5 and 8
xdata1 = np.linspace(5., 8., num_points)
xdata2 = xdata1

ydata1 = 11.86*np.cos(2*np.pi/0.81*xdata1-1.32) + 0.64*xdata1+4*((0.5-np.random.rand(num_points))*np.exp(2*np.random.rand(num_points)**2))
ydata2 = -32.14*np.cos(2*np.pi/0.8*xdata2-1.94) + 0.15*xdata2+7*((0.5-np.random.rand(num_points))*np.exp(2*np.random.rand(num_points)**2))

Python, specifically in the Scipy package, has many ways to fit data. You may have head of "least-squares" method. Python has this, but it isn't actually the best method, especially if you have uncertainties with your data. Instead I recommend the "Orthogonal Distance Regression" or ODR method. It support errors, and in simple cases will reduce to the "least-squares" method automatically. So lets import ORD and do an example fit.

## Now Orthogonal Distance Regresssion

In [207]:
from scipy import odr #for ODR method, if you know ahead of time you will use this, 
                        #it is best to include it in your original import cell

In [208]:
#this function depends on p and x, p is an array of parameters, which will be found by using least_squares
#x is the x data and the function will return the best guess at the y given the fit parameters
#you can change this to reflect whatever functional form you are fit, the variables (maybe use t instead of x if you have time)
def fitfunc(p,x):
    y = p[0]*np.cos(2*np.pi/p[1]*x+p[2]) + p[3]*x
    return y

#next we make the fitfunction a model that odr can read
model = odr.Model(fitfunc)

     
#Define your data, here we will use the fake data we made up above.
#If you have real data you would do something like xdata = np.aray([0.,1.,4.,5.])
#where you have replaced the numbers with you actual data
xdata = xdata1
ydata = ydata1

#similarly, make an array with your list of errors. Below we assume a fixed relative error
#and just multiply the x and y data by a constant 5%
xerrs = xdata*0.01
#xerrs= np.array([.1,.2,.3])
yerrs = ydata*0.10


#now make your data a data object. if you don't have errors just delete the sx=xerrs and sy=yerrs
data1 = odr.RealData(xdata,ydata,sx=xerrs,sy=yerrs)

#lastly make an initial guess at your parameters. this should have the same number of entries as the
#number of paramters in your fitfunc
initial = np.array([-15., 0.8, 0., -1.])

In [209]:
#here we can run the ODR fitting function
#this line runs the routine, you give it your data, model and initial guess (ORD calls it beta0) and set the output equal to 
#somthing like odrfit
odrfit1 = odr.ODR(data1,model, beta0=initial)

#Tell it to Run ODR
results1 = odrfit1.run()
#Print Results
results1.pprint()

Beta: [-14.49731911   0.78717084   0.35047649   0.4733031 ]
Beta Std Error: [0.65093795 0.00732561 0.46858625 0.08028585]
Beta Covariance: [[1.97196714e-01 3.15590254e-04 2.04207745e-02 1.40497821e-03]
 [3.15590254e-04 2.49751370e-05 1.58298435e-03 2.31101373e-05]
 [2.04207745e-02 1.58298435e-03 1.02187923e-01 1.60670526e-03]
 [1.40497821e-03 2.31101373e-05 1.60670526e-03 2.99984281e-03]]
Residual Variance: 2.1487184523010976
Inverse Condition #: 0.00021398525199994042
Reason(s) for Halting:
  Iteration limit reached


In the output from the fit there are three inportant things, Beta (called as "beta"), beta std error (Called as "sd_beta") and Residual Variance (res_var).

**beta** --> are the parameters found from the fit

**sd_beta** --> are the uncertainties of each parameter

**res_var** --> measure of the goodness of fit per degree of freedom. A smaller number is better! Similar to the reduced chi-squared, so that a value near one indicates a good fit. Large numbers suggest a poor fit while really small numbers may suggest the error bars are too big. 

In [210]:
#Lets run it again with no error bars
#with no error bars. The model and data is the same, except there are no errors now!

#Data
xdata = xdata1
ydata = ydata1

data2 = odr.RealData(xdata,ydata)

initial = np.array([-15., 0.8, 0., -1.])

odrfit2 = odr.ODR(data2,model, beta0=initial)
#Run ODR
results2 = odrfit2.run()
#Print Results
results2.pprint()

Beta: [-11.27262002   0.7876729    0.18993183   0.57437529]
Beta Std Error: [0.34380333 0.11107483 7.35822592 0.05127624]
Beta Covariance: [[ 5.69510462e-02 -3.77177093e-04  2.21381099e-02  1.87785865e-03]
 [-3.77177093e-04  5.94446660e-03  3.89808595e-01 -6.17926961e-05]
 [ 2.21381099e-02  3.89808595e-01  2.60872188e+01  2.14753628e-03]
 [ 1.87785865e-03 -6.17926961e-05  2.14753628e-03  1.26681692e-03]]
Residual Variance: 2.075479534026371
Inverse Condition #: 0.00019644160606864994
Reason(s) for Halting:
  Iteration limit reached


In [211]:
#Now lets plot ther results
time = np.linspace(xdata.min(), xdata.max(), 100) #make a range of xvalues to use with the fit function

fig,ax=plt.subplots(dpi=200)
ax.errorbar(xdata, ydata, xerr=xerrs, yerr=yerrs,fmt= "ro",markersize=5) #plot of the data with error bars
ax.plot(time, fitfunc(results1.beta, time),"r-") # Plot of the fit
ax.plot(time, fitfunc(results2.beta, time),"b-") # Plot of the fit



# Legend the plot
ax.set_title("Oscillations in of a Spring")
ax.set_xlabel("time [ms]")
ax.set_ylabel("displacement [um]")
ax.legend(('errors', 'no errors','data'),loc='upper left')


ax.text(0.5, 0.07,
         'freq1 :  %.3f kHz \n x freq2 - no errors: %.3f kHz' %(1/results1.beta[1],1/results2.beta[1]),
         fontsize=10,
         horizontalalignment='right',
         verticalalignment='center',
         transform=ax.transAxes)

ax.text(0.55, 0.07,
         'res_var1 :  %.3f  \n  res_var2: %.3f ' %(results1.res_var,results2.res_var),
         fontsize=10,
         horizontalalignment='left',
         verticalalignment='center',
         transform=ax.transAxes)

<IPython.core.display.Javascript object>

Text(0.55, 0.07, 'res_var1 :  2.149  \n  res_var2: 2.075 ')

Lets Practice! Using either the ideal gasl law data or the height and wingspan data, see if you can fit the data to a line, i.e. your model should be something of the form y = m*x+b, and then make a graph showing the fit over the data. Remember to change variable names and the name of your fit function and model so you don't overwrite previous work.

------
## Things below are optional. If you want to make fancy looking plots!

### You can also make your plots look really fancy with different styles. 

To see what is available use this command 
    
    print(plt.style.available)
    
There is a gallary [https://tonysyu.github.io/raw_content/matplotlib-style-gallery/gallery.html](https://tonysyu.github.io/raw_content/matplotlib-style-gallery/gallery.html)

Set a style with

    plt.style.use('fivethirtyeight')

for instance to make things look like [fivethirtyeight.com](http://fivethirtyeight.com/)


In [212]:
print(plt.style.available)

['Solarize_Light2', '_classic_test_patch', '_mpl-gallery', '_mpl-gallery-nogrid', 'bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'seaborn', 'seaborn-bright', 'seaborn-colorblind', 'seaborn-dark', 'seaborn-dark-palette', 'seaborn-darkgrid', 'seaborn-deep', 'seaborn-muted', 'seaborn-notebook', 'seaborn-paper', 'seaborn-pastel', 'seaborn-poster', 'seaborn-talk', 'seaborn-ticks', 'seaborn-white', 'seaborn-whitegrid', 'tableau-colorblind10']


In [213]:
# change to the style of Website 538 

with plt.style.context(('fivethirtyeight')):
    x = [0.0,1.0,2.0,3.0]
    y1 = [1.0,3.0,4.0,5.0]
    y2 = [5.0,6.0,4.0,7.0]

    plt.plot(x,y1,label='red',marker='o',linestyle='None')
    plt.plot(x,y2,label='blue',marker='o',linestyle='None')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.title('x verus y')
    plt.legend()

In [214]:
#I like this one "seaborn-colorblind"
with plt.style.context(('seaborn-colorblind')):
    x = [0.0,1.0,2.0,3.0]
    y1 = [1.0,3.0,4.0,5.0]
    y2 = [5.0,6.0,4.0,7.0]

    plt.plot(x,y1,label="kids",color='C3',marker='o',linestyle='None')
    plt.plot(x,y2,label='adults',color='C4',marker='o',linestyle='None')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.title('x verus y')
    plt.legend()

In [215]:
#how about like xkcd. though becareful because afterwards it will change all subsequent plots
with plt.xkcd():
    plt.xkcd()
    x = [0.0,1.0,2.0,3.0]
    y1 = [1.0,3.0,4.0,5.0]
    y2 = [5.0,6.0,4.0,7.0]

    plt.plot(x,y1,label='orange',)
    plt.plot(x,y2,label='blue')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.title('x verus y')
    plt.legend()
    plt.grid()